name: CI Build

on:
  push:
    branches: [develop]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  pull_request:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  # Android Test
  build-android:
    runs-on: windows-2022
    name: Android Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TestApp/TestApp.csproj

      - name: Build Android
        run: dotnet build TestApp/TestApp.csproj -c Release -f net6.0-android --no-restore

      - name: Test Android
        run: dotnet test TestApp/TestApp.csproj -c Release -f net6.0-android --no-restore

  # Windows test
  build-windows:
    runs-on: windows-2022
    name: Windows Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TestApp/TestApp.csproj

      - name: Build Windows
        run: dotnet build TestApp/TestApp.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore

      - name: Test Windows
        run: dotnet test TestApp/TestApp.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore

  # iOS Test
  build-ios:
    runs-on: macos-12
    name: iOS Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TestApp/TestApp.csproj

      - name: Build iOS
        run: dotnet build TestApp/TestApp.csproj -c Release -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Test iOS
        run: dotnet test TestApp/TestApp.csproj -c Release -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

  # MacCatalyst Test
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TestApp/TestApp.csproj

      - name: Build MacCatalyst
        run: dotnet build TestApp/TestApp.csproj -c Release -f net6.0-maccatalyst --no-restore -p:BuildIpa=True

      - name: Test MacCatalyst
        run: dotnet test TestApp/TestApp.csproj -c Release -f net6.0-maccatalyst --no-restore -p:BuildIpa=True
